name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.gitignore'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: sjc.vultrcr.com/fotoowl
  IMAGE_NAME: echoo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Vultr Container Registry
      uses: docker/login-action@v3
      with:
        registry: https://sjc.vultrcr.com/fotoowl
        username: ${{ secrets.VULTR_REGISTRY_USERNAME }}
        password: ${{ secrets.VULTR_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: sjc.vultrcr.com/fotoowl/echoo:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update deployment status
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Docker image built and pushed successfully!"
        echo "Image: sjc.vultrcr.com/fotoowl/echoo:latest"
        echo "Platforms: linux/amd64, linux/arm64"
        echo "Ready for Kubernetes deployment!"